apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
spec:
  storageClassName:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: kafka
    fsType: ext4
